services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.ssh
      target: development
    command: bash /app/start.sh --reload
    depends_on:
      - postgres
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
    volumes:
      - ./:/app
    ports:
      - 80:80

  postgres:
    image: postgres:13.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
