FROM python:3.9.8-slim

COPY ./requirements.basic.txt start.sh /app/

RUN apt-get update && apt-get install -y git && \
	pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./app /app

WORKDIR /app

CMD [ "bash", "/app/start.sh" ]
