stages:
  - build
  - pages

build-image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  only:
    - main
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --target production -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

pages:
  image:
    name: registry.gitlab.com/haseeb-slides/docker-as-a-dev-tool
  stage: pages
  only:
    - main
  script:
    - mv /reveal public
  artifacts:
    paths:
      - public
