version: '3.8'

services:
  revealjs:
    image: webpronl/reveal-md:latest
    command: /slides --watch --css styles/main.css
    volumes:
      - ./:/slides
    ports:
      - 1948:1948
      - 35729:35729
