services:
  presentation:
    build:
      context: .
      target: main
    volumes:
        - ./index.html:/reveal/index.html
        - ./slides.md:/reveal/slides.md
        - ./css/zoe.css:/reveal/dist/zoe.css
        - ./css/code.css:/reveal/dist/code.css
    ports:
      - 8000:8000
      - 35729:35729