stages:
  - test

format:check:
  stage: test
  image: docker
  services:
    - docker:dind
  script:
    - make format

test:
  stage: test
  image: docker
  services:
    - docker:dind
  script:
    - make test
