services:
  presentation:
    build:
      context: .
      target: production
      # cache_from:
      #   - registry.gitlab.com/hmajid2301/talks/gitlab-runners-and-dind
    volumes:
      - ./index.html:/reveal/index.html
      - ./slides.md:/reveal/slides.md
      - ./images/:/reveal/images/
    ports:
      - 127.0.0.1:8000:8000
      - 127.0.0.1:35729:35729
